### ISSUE TITLE
¿website! 

### ISSUE THREAD

**Issue by joehand** [dat-land/comm-comm#21]
Would a website be helpful to get folks aware of the community calls? I put together https://dat-comm-comm.netlify.com/ while watching some basketball =). I could add it here or keep it in it's own repo.

The issues are pulled in on each build (Can add webhook for new issue => netlify build).

**Comment by martinheidegger** [comment]
in a website branch?

**Comment by joehand** [comment]
Yep that'd work! Could also be a subdirectory.

**Comment by dpaez** [comment]
Cool work @joehand !!! If I can help you with something let me know. 
Thinking about hooks, maybe with a _new issues_ hook (with the **meeting** label?), we can update the site. Something like you are doing now, I guess. The new branch would be used when we add notes, which are linked to a meeting. 

In this case, I think maybe a _merge on master_ hook will be more useful. What do you say?

**Comment by karissa** [comment]
Yeah, having some sort of hooks into the github would be nice, often people forget to update websites if we're used to using github as the medium of comm

**Comment by joehand** [comment]
Yep, I setup a hook to rebuild on **_any_** issue update (that is the best github can do), see [hook here](https://github.com/dat-land/comm-comm/settings/hooks/86724322) if admin. I'm only pulling in open issues with the meeting label for the site.

Not quite following the other points:

> The new branch would be used when we add notes, which are linked to a meeting.

> In this case, I think maybe a _merge on master_ hook will be more useful. What do you say?

**Comment by dpaez** [comment]
About the other points, they are only valid if we want to show the meeting notes on the new comm-comm site. That is why I mention the hook on merge to master (when a PR got merged). We usually create a PR for the meeting notes. But maybe we can just link to `/meeting-notes` and that will be much simpler.

**Comment by joehand** [comment]
Ah yes, makes sense! I thought about doing that but seemed like a harder design problem =). I'll PR to add subdir.
