### ISSUE TITLE
20190320 - DAT Night

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/comm-comm#37]
Offline meeting in Portland (OR), United States at [Rumors](https://www.google.com/maps/place/728+SE+20th+Ave,+Portland,+OR+97214/@45.5175017,-122.6459679,17.81z/data=!4m5!3m4!1s0x5495a0a2b1682707:0xeda19240e503223!8m2!3d45.5176174!4d-122.645346)

Time: 20 Mar 2019, 18:00 America/Los_Angeles

https://datnight.org

**Comment by martinheidegger** [comment]
Hello @joehand, I noticed that datnight is next week so I took the liberty to add it to the calendar.

cheers!

cc. @whoisgina

**Comment by whoisgina** [comment]
Thanks @martinheidegger!

**Comment by joehand** [comment]
Dat night was a success! 

We has short talks by Danielle, about Dat + Scholarly publishing, and Darius, about his fellowship experience so far (blog post coming out very soon). 

Then we talked about what we'd like Dat night to be and had lots of good ideas contributed (which maybe @whoisgina has documented).

**Comment by whoisgina** [comment]
Yes! It was a lovely casual evening with lots of snacks and friends and ideas! Everyone wrote down a bit about what they'd like to get from Dat Night, decentralized tech that they're interested in exploring, potential projects and collaborators:

<img width="968" alt="Screen Shot 2019-03-21 at 12 39 20 PM" src="https://user-images.githubusercontent.com/2815123/54780194-5e60d680-4bd6-11e9-9cea-8c0c4c108911.png">
<img width="957" alt="Screen Shot 2019-03-21 at 12 39 11 PM" src="https://user-images.githubusercontent.com/2815123/54780195-5ef96d00-4bd6-11e9-95f3-9ab5d1b698a1.png">
<img width="969" alt="Screen Shot 2019-03-21 at 12 39 00 PM" src="https://user-images.githubusercontent.com/2815123/54780196-5ef96d00-4bd6-11e9-949c-8814f2122429.png">

Which @joehand and I will use to inform future events! I'd like to do it monthly if possible, so look out for one in April. ✨

**Comment by joehand** [comment]
And here is the blog post from Darius! https://blog.datproject.org/2019/03/22/three-protocols-and-a-future-of-the-decentralized-internet/
