### ISSUE TITLE
meeting at 35c3

### ISSUE THREAD

**Issue by Frando** [dat-land/comm-comm#4]
Hi,
is anyone at 35c3 in Leipzig?

If so, let's meet:

28th dec, 15:00 CET, !decentral assembly
https://events.ccc.de/congress/2018/wiki/index.php/Session:Dat_project_and_community_meetup

**Comment by ralphtheninja** [comment]
Just for the record. We had two smaller meetings, briefly documented in this hackpad https://hackmd.io/qNZAcy1CSKyz5vIqakB5Kw#

**Comment by Frando** [comment]
Just pinging some people who were there. Feel free to add more things to the meeting notes (links etc)

@cblgh @krl @Powersource

**Comment by dpaez** [comment]
Hi all 👋
@Frando, maybe we can make a PR with these 35c3 meeting notes. What do you think?

**Comment by martinheidegger** [comment]
Ping @Frando

**Comment by Frando** [comment]
Sorry for not replying earlier. Looks all good!
