### ISSUE TITLE
20190517 - Data Terra Nemo

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/comm-comm#42]
@mafintosh @karissa @pfrazee @substack and @whoisgina will be presenting at this years Data Terra Nemo in Berlin.

Time: 17 May 2019, 09:00 Europe/Berlin
End: 18 May 2019, 20:00 Europe/Berlin

https://dtn.is/#about

**Comment by Frando** [comment]
There was already some talking about having a community meeting / hacking gathering around that date. AFAIK nothing further is settled so far, or is it?

**Comment by RangerMauve** [comment]
@Frando We haven't planned anything concrete yet AFAIK. 😅

**Comment by karissa** [comment]
Yes I'd like to organize a gathering with folks that week, perhaps we could rent a flat in Berlin as "home base" where people can come and go as they please. It would also be nice to have one day that's public, perhaps lightning talks followed by a day of hacking.

If folks are Interested in something like this we could sponsor one flat for a few days with the handshake money.

Want to get on a call soon to discuss?

**Comment by Frando** [comment]
Sounds good! Next week, e.g. tuesday 6pm CET/Berlin = 10am PDT/California?

**Comment by karissa** [comment]
Can we discuss this during the next comm comm that is Europe and pacific friendly?

**Comment by cblgh** [comment]
+1 ill be at dtn and there the week before to hack on dat with y'all

**Comment by lachenmayer** [comment]
Would love to get involved with this - am heading over to Berlin for DTN too & would be cool to head over a bit earlier or stay afterwards to hack on some Dat stuff! :)

**Comment by Frando** [comment]
Cool!

let's take the next comm-comm then:

[*#44* 20190328 - meeting](#44)
> Just an hour hanging out and talking about DAT stuff.
> Time: 28 Mar 2019, 18:00 GMT
> https://meet.jit.si/DATcomm-comm

**Comment by martinheidegger** [comment]
@karissa @joehand Do we have a collection of resources or media created around DTN?
