### ISSUE TITLE
20190519 - DAT Hack Meeting

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/comm-comm#57]
A whole mini conference around DAT and hyper*!

Time: 19 May 2019, 13:00 GMT

More: https://events.datproject.org/
RSVP: https://events.datproject.org/rsvp/

**Comment by martinheidegger** [comment]
@karissa How did that go? Did you make some notes? Are there some links?

**Comment by RangerMauve** [comment]
Here's a link to the livestream that was recorded during the event: https://vimeo.com/337090026

**Comment by decentral1se** [comment]
Was also asking for slides/video/etc. over at https://dat.discourse.group/t/dat-hack-meeting-slides-video-audio-etc/30/7. Thanks for sharing this video!
