### ISSUE TITLE
20190719 - dwebcamp

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/comm-comm#82]
> A meet-and-greet and workshop for folks who are actively building these peer-to-peer databases, as well as for new people who are interested in getting involved. 

Time: 19 Jul 2019, 10:15 America/Los_Angeles

RSVP: https://dwebcamp2019.sched.com/event/RdZp
Location: A farm near San Francisco

**Comment by martinheidegger** [comment]
@karissa how did it go?

**Comment by RangerMauve** [comment]
I think @pfrazee and @noffle were also there for the workshop. :O

**Comment by pfrazee** [comment]
I thought it went pretty well! Lots of people interested, lots of good conversation about usability and doable solutions.

**Comment by noffle** [comment]
It was more chaotic than I expected! We broke into several smaller groups to discuss different facets of peer-to-peer applications, and then came back together to summarize. I'm not sure if anybody took notes.

**Comment by martinheidegger** [comment]
Closing this issue without notes :)
